<?php

?>

	<div id="createSaleLightBox" class="createSaleLightBox lightBox">
        <div class="createSaleTitle">
            <p>Make a selection to start selling your stuff.</p>
        </div>
        <a href="AddImage.php">
            <div class="OneSale">
                <p class="SubTitle">One Sale</p>
                <img class="LoginInPic" src="images/icons/onesale_red.png" alt="example pics"/>
                <p class="SubText">Best for selling one item. </p>
                <p class="SubText">Upload+Tag+Price+Sell=Easy.</p>
            </div>
        </a>
        <a href="garagerPageSetup.php">
            <div class="MultiSale">
                <p class="SubTitle">Multi-Sale</p>
                <img href="garagerPageSetup.php"class="LoginInPic" src="images/icons/multisale_red.png" alt="example pics"/>
                <p class="SubText">Typically for creating a listing</p>
                <p class="SubText">of multiple items for sale.</p>
            </div>
        </a>
    </div>
<?php

?>