<?php
?>
<div id="ResetPWDLightBox" class="lightBox">
	<div class="errorMessage">
    </div>
<p id="topTitleLog"><b> Or Enter your email below to reset your password.</b></p>
<div class="resetPWDBox">
<form action="" method="POST" id="reset_pwd_form">
<p>Enter your email to receive a link to reset your password.</p>
<input id="reset_email" type="email" name="reset_email" required>
<input type='hidden' name='submitted' id='submitted' value='1'>
<input type="submit" value="submit" name="submit" id="reset_pwd_button">
</form>
</div>
</div>

<?php
?>